version: '3.8'

services:
  miao-kit:
    image: lun1ry/miao-kit:latest
    container_name: miao-kit
    ports:
      - "3000:3000"
    volumes:
      # 持久化图片存储目录
      - ./uploads:/app/public/uploads
      # 持久化转发规则配置
      - ./forward-rules.json:/app/forward-rules.json
    environment:
      # 服务端口（可选，默认3000）
      - PORT=3000
      # Node.js 环境
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

